### ISSUE TITLE
Modid incorrect format for dependency usage

### ISSUE THREAD

**Issue by Mad-Gnome** [Zflocco/Swordz#1]
Your modid is listed with a capitalized letter
 "modid": "Swordz",

This prevents server from listing it as a dependency if we want to patch it with a server mod at all, ie disable Excavator.  

When I list it as a dependent: -  "modid": "swordz", it re-downloads the mod from the moddb, restarts, and then wants to do the process again.

Basically, in your modinfo, please change
  "modid": "Swordz",
to
  "modid": "swordz",
I'd love to be able to use this.  I made this change, tested it in SP, and my server patch was able to recognize it as a dependency and patch it perfectly.

**Comment by Zflocco** [comment]
Noted and fixed in 1.1.7
