### ISSUE TITLE
Incompatibility with xskills

### ISSUE THREAD

**Issue by Mad-Gnome** [Zflocco/Swordz#2]
Specifically: Blades that can be sharpened.

When you upgrade the blade by crafting it with a sharpening stone the quality modifier gets lost.

My server did a temporary fix for this, we noticed the Zweihander still works when crafted because the Zweihander Crossguard has a quality modifier when smithed and this modifier transfers over to the final weapon.
So what we did (since we are not modelers to add a 'handguard' to all the other blades) was we replaced the stick in the recipe for them all with a haft, the haft keeps the quality modifier.  After the blade is upgraded to the honed version and crafted, the weapon will still keep the final quality modifier this 
![image](https://github.com/Zflocco/Swordz/assets/23144159/525e8ca4-6177-4cb5-9abe-1269a8222eff)
way.
![image](https://github.com/Zflocco/Swordz/assets/23144159/4a7c06ad-f151-45aa-9484-952ab44804eb)

**Comment by Zflocco** [comment]
Should be fixed in 1.1.8 , marking as closed/completed but might've missed one or two.
