### ISSUE TITLE
Short Swords do no damage

### ISSUE THREAD

**Issue by Mad-Gnome** [Zflocco/Swordz#3]
The recipes are all in there to make it, but none of the short sword variants actually do anything damage wise.

In the itemtypes folder there is no shortsword either, I am assuming this is why?

In the forum description for the Shortsword is says "*Xskills : Tool Mastery as it's a "knife", but tool mastery only covers pickaxe, axe, hammer and hoe.

**Comment by Zflocco** [comment]
> The recipes are all in there to make it, but none of the short sword variants actually do anything damage wise.
> 
> In the itemtypes folder there is no shortsword either, I am assuming this is why?

What version of the game, what version of the mod, and what other mods are you running? Run the game without any other mods and see if it's still lacking damage.

**Comment by Mad-Gnome** [comment]
Running VS 1.19.7
Swordz 1.1.6

The only weapon with the issue is the short sword, every other weapon tested so far on my server has been working for my players.

Has the same issue on a heavily modded (100+) server and in SP with just the Swordz mod installed.

**Comment by Zflocco** [comment]
Found and fixed for 1.1.7
