### ISSUE TITLE
Config option not working for naginata

### ISSUE THREAD

**Issue by Mad-Gnome** [Zflocco/Swordz#5]
VS 1.19.8, Swordz 1.1.7

Enabled the Naginita in the config returns this error:
  "naginataenabled": true,
  
19.5.2024 11:26:51 [Error] Patch 150 (target: swordz:recipes/grid/polearms/naginata.json) in swordz:patches/disabler.json failed because supplied path /enabled is invalid: The json path /enabled was not found. No such element 'enabled' at the root path

**Comment by Zflocco** [comment]
Is it craftable, and it's just crapping out an error?

**Comment by Mad-Gnome** [comment]
No crafting recipe for the three variations of the weapon, nor smithing recipes for the blade itself.

**Comment by Zflocco** [comment]
Fixed for 1.1.8.
