### ISSUE TITLE
Mismatching Variant Code on Zweihander

### ISSUE THREAD

**Issue by splitlungs** [Zflocco/Swordz#6]
Zweihander's variantCode "blade" is unlike all other itemtypes/swords/ that use variantCode "sharpness".

This should be a standardized code across all itemtypes for consistency.

**Comment by splitlungs** [comment]
The long version is that I'm working on mod integration with KRPG Enchantment, and I almost missed that variantCode was different. I don't want things to randomly break later if you're deciding to go with a different naming convention.
Thanks!

**Comment by Zflocco** [comment]
Changed in 1.1.8
