### ISSUE TITLE
Titanium Knife doesn't work in grid crafting

### ISSUE THREAD

**Issue by McBainWRX** [Zflocco/Swordz#7]
In version 1.1.7, the titanium knife isn't a recognized knife for purposes of recipes done in the crafting grid such as scrapping soaked hides or any of the expanded foods recipes that involve knives.  It does work correctly for in world knife uses such as skinning animals or cutting pie.  I have not tested the other fantasy metals but they might have the same issue.

**Comment by Zflocco** [comment]
Fixed 1.1.8
